//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADONETDEMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderid { get; set; }
        public Nullable<int> custid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string product { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
