//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADONETDEMO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.courses = new HashSet<course>();
        }

        public int studentid { get; set; }
        [Required(ErrorMessage = "plese enter name")]
        [MinLength(3, ErrorMessage = "please enter min 3 characters")]
        [RegularExpression("[a-z]+",ErrorMessage ="Enter valid name")]
        public string studentname { get; set; }
        [Required(ErrorMessage = "Please enter class")]
        [Range(1,10,ErrorMessage ="Invalid Class")]
        public Nullable<int> sclass { get; set; }
        [MinLength(3, ErrorMessage = "Enter valid city")]
        public string saddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course> courses { get; set; }
    }
}
