// <auto-generated />
namespace CodeFirstAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mySchema3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mySchema3));
        
        string IMigrationMetadata.Id
        {
            get { return "202409210641182_mySchema3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
